// wallet
export const FETCH_ALL = 'FETCH_ALL'
export const FETCH_ONE = 'FETCH_ONE'
export const UPDATE_ONE = 'UPDATE_ONE'
export const DELETE_ACTIONS = 'DELETE_ACTIONS'
// shop
export const FETCH_SHOP_INDEX = 'FETCH_SHOP_INDEX'
export const FETCH_SHOP_INDEX_GOODS = 'FETCH_SHOP_INDEX_GOODS'
export const FETCH_SHOP_CAT_GOODS = 'FETCH_SHOP_CAT_GOODS'
export const FETCH_SHOP_GOODS_DETAIL = 'FETCH_SHOP_GOODS_DETAIL'
export const FETCH_SHOP_GOODS_SPECS = 'FETCH_SHOP_GOODS_SPECS'
export const FETCH_SHOP_GOODS_CATEGORY = 'FETCH_SHOP_GOODS_CATEGORY'
export const FETCH_SHOP_GOODS_SPECS_SET = 'FETCH_SHOP_GOODS_SPECS_SET'
export const FETCH_SHOP_SUBMIT = 'FETCH_SHOP_SUBMIT'
export const FETCH_SHOP_ADDRESS = 'FETCH_SHOP_ADDRESS'
export const FETCH_SHOP_ADDRESS_ID = 'FETCH_SHOP_ADDRESS_ID'
export const FETCH_SHOP_ADDRESS_LIST = 'FETCH_SHOP_ADDRESS_LIST'
export const FETCH_SHOP_CONFIRM_DATA = 'FETCH_SHOP_CONFIRM_DATA'
export const FETCH_SHOP_MEMBER = 'FETCH_SHOP_MEMBER'
export const FETCH_SHOP_CART = 'FETCH_SHOP_CART'
export const FETCH_ROUTER_LOADING = 'FETCH_ROUTER_LOADING'
export const FETCH_DIY_PAGE = 'FETCH_DIY_PAGE'

// takeout
export const FETCH_TAKEOUT_INDEX = 'FETCH_TAKEOUT_INDEX'

// auth
export const AUTH_CHECK = 'AUTH_CHECK'
export const JWT_AUTH_LOGIN = 'JWT_AUTH_LOGIN'
export const AUTH_LOGIN_OUT = 'AUTH_LOGIN_OUT'
export const JWT_AUTH_LOGIN_CALLBACK = 'JWT_AUTH_LOGIN_CALLBACK'
